### ISSUE TITLE
Can't export/import profile: Cannot decrypt tox save file

### ISSUE THREAD

**Issue by dennisnez** [Zoxcore/Antidote#122]
We get an error when trying to import a save.tox file that was exported from another ios device:

  Cannot decrypt tox save file
  Password is wrong or file is corrupted

Is anyone else able to export/import profiles?

**Comment by Tha14** [comment]
@dennisnez Hey, I will give it another go but as I said, it worked before for me but it was on the same device.

**Comment by Tha14** [comment]
@dennisnez So, I tried importing two profiles(I had an old one aswell) and both worked. I believe the error you get is due to inputting the wrong password at the login stage. The tox save is encrypted so a password is always required after importing the profile.

**Comment by dennisnez** [comment]
Yes you're right. Sorry for the distraction! Thank you for your time!
