### ISSUE TITLE
TOR inside

### ISSUE THREAD

**Issue by SiNaPsEr0x** [Zoxcore/Antidote#140]
Can add TOR or proxy setting socks?

**Comment by zoff99** [comment]
we started a test with tor inside. but this is very difficult on iOS, and it was not very stable.
for now the only thing you can do is use a VPN for you iPhone.

maybe somebody can help us to add tor inside Antidote?

**Comment by SiNaPsEr0x** [comment]
Ok but add a flag for socks5 with login e pass? I have mine dante-server and tor ... This would be the fastest and easiest solution

**Comment by SiNaPsEr0x** [comment]
For tor For example, part of the code that is inserted inside can be used tor browser 

[HERE](https://github.com/OnionBrowser/OnionBrowser)

**Comment by donotsdubba** [comment]
Tor is very well-known to be a honeypot by the way, it's inherent to the way it works. Not to mention Tor Browser's curated issue tracking (use Wayback Machine on it to see issues they deleted that exposed them).
