### ISSUE TITLE
Language italian

### ISSUE THREAD

**Issue by SiNaPsEr0x** [Zoxcore/Antidote#141]
Why is the Italian language not accepted? I have complete The translate on weblate

I saw that the strings have already been translated but once installed the language of the device is not received

**Comment by zoff99** [comment]
that seems very strange. is your phone set to italian correctly? are only some texts not translated, or ALL texts not translated?

**Comment by SiNaPsEr0x** [comment]
On the App Store it doesn’t even have the Italian language in the translated languages, even on my other devices it doesn’t appear in Italian


![image](https://user-images.githubusercontent.com/5438823/199996413-31a1ba21-7e1c-459e-b0bd-658d27a76a05.png)

**Comment by zoff99** [comment]
ok let us look into this. i dont have an iphone here now.

**Comment by Tha14** [comment]
The project doesn't have an italian translation. It needs to be set in the project.
![image](https://user-images.githubusercontent.com/5931740/200007996-f96f9c6f-73ce-42e5-afc1-c0af957fee40.png)

**Comment by SiNaPsEr0x** [comment]
But The translate italian is Live on weblate... when introduce it?


https://hosted.weblate.org/languages/it/antidote/

**Comment by zoff99** [comment]
ok. now i see it. let me make a fix ...
