### ISSUE TITLE
Copy-pasting new contact toxid doesn't enable Send button

### ISSUE THREAD

**Issue by dennisnez** [Zoxcore/Antidote#149]
When trying to add a new contact, pasting a toxid into the (too) big textarea doesn't enable the "Send" button, but manually backspacing and typing the last character does.

Ie. that "Send" button only seems to trigger on regular keypress events, but not on pastes?

**Comment by zoff99** [comment]
@dennisnez i tried it now on the emulator and the send button is activated when pasting a ToxID.
does the clipboard contain any special characters or spaces?

can you give more details? what ios version? what app version? please use the bug template.

**Comment by dennisnez** [comment]
iOS 16.1.1
Antidote 1.4.24

Does it work with anyone else's (non-emulated) iphone? :p

**Comment by dennisnez** [comment]
![addc](https://user-images.githubusercontent.com/3186040/208507962-ce9279b7-ed4a-45b6-8db6-f59b47e2d124.jpg)
(It's not possible to enter more than those 76 characters there.)

**Comment by zoff99** [comment]
0499D1D05FF5F9D3C7776B0EC8F9CE876D20760FFC6EC4E4C07C6C082B73005F000000697DFC

just did a quick online OCR to copy and paste it

**Comment by zoff99** [comment]
a friend confirmed the bug on a real iphone. sadly i don't see it on the emulator. my development macos hardware is not in operation at this time

**Comment by zoff99** [comment]
solved by #151
