### ISSUE TITLE
Release v1.4.25

### ISSUE THREAD

**Issue by Tha14** [Zoxcore/Antidote#157]
Create new release for v1.4.25

**Comment by zoff99** [comment]
release tagged and ready to publish

**Comment by Tha14** [comment]
Need changelog.

**Comment by zoff99** [comment]
https://github.com/Zoxcore/Antidote/blob/develop/CHANGELOG.md

changelog updated. but some issues were closed by stale-bot, and are not fixed.
not sure if you want to mention those on the app store
